[package]
name = "MemeDAORoyale"
version = "1.0.0"
authors = []

[addresses]
memedao = "_"

[dev-addresses]
memedao = "0xCAFE"

[dependencies.AptosFramework]
local = "/tmp/aptos-fw/aptos-move/framework/aptos-framework"

[dev-dependencies]
